### ISSUE TITLE
Not helpfull error message, when examples have no description

### ISSUE THREAD

**Issue by Jentsch** [ThoughtWorksInc/sbt-example#17]
Hi I like this tool a lot. But when no description is given failing tests produce a not very helpful error message. For example in 
```
@example
{{{
  2 should be(3)
}}}
```
the message is
```
org.scalatest.exceptions.NotAllowedException was thrown inside "ecspec" -, construction cannot continue: "org.scalatest.exceptions.NotAllowedException was thrown inside "TestCase" -, construction cannot continue: "Assertion should be put inside in clause, not - clause."" (sbt-example-generated.scala:xxx)
```

I could try to come up with a fix, but I not sure what a good solution would be. Allow examples without description or throwing an explicit error that points to the broken line?

**Comment by Atry** [comment]
Fixed in #18
